### ISSUE TITLE
maintenance: format code with cargo fmt

### ISSUE THREAD

**Issue by swanandx** [najamelan/ws_stream_tungstenite#12]
Currently the code isn't formatted with `cargo fmt` which makes it harder to contribute, as most of IDEs will auto format code on saving, it causes huge unnecessary diff. Formatting with `cargo fmt` should also help in improving redability!

Let me know wdyt :100:

**Comment by najamelan** [comment]
Please read my answer here:
https://github.com/thespis-rs/thespis/issues/1
