### ISSUE TITLE
WsStream::new( ) mismatched types with async-tungstenite 0.24

### ISSUE THREAD

**Issue by qgerman2** [najamelan/ws_stream_tungstenite#16]
with async-tungstenite 0.24 as a dependency, the following code fails

```
use async_tungstenite::accept_async;
use async_tungstenite::tokio::TokioAdapter;
use log::*;
use std::{io, net::SocketAddr, str::FromStr};
use tokio::net::{TcpListener, TcpStream};
use ws_stream_tungstenite::*;

#[tokio::main]
async fn main() {
    let addr = SocketAddr::from_str("127.0.0.1").unwrap();
    let socket = TcpListener::bind(&addr).await.unwrap();
    loop {
        tokio::spawn(connection(socket.accept().await));
    }
}

async fn connection(stream: Result<(TcpStream, SocketAddr), io::Error>) {
    let Ok((stream, addr)) = stream else { return };
    let Ok(stream) = accept_async(TokioAdapter::new(stream)).await else {
        return;
    };
    info!("CONECTADO {}", addr);
    let stream = WsStream::new(stream);
}
```

with error

```
error[E0308]: mismatched types
   --> src\main.rs:23:32
    |
23  |     let stream = WsStream::new(stream);
    |                  ------------- ^^^^^^ expected `WebSocketStream<_>`, found `WebSocketStream<TokioAdapter<TcpStream>>`
    |                  |
    |                  arguments to this function are incorrect
```

with Cargo.toml dependencies as

```
[dependencies]
futures = "^0.3"
log = "0.4.20"
tokio = {version="1.36.0", features=["full"]}
ws_stream_tungstenite = "0.11.0"
async-tungstenite = {version="0.24", features=["tokio-runtime"]}
```

however, if async-tungstenite version is set to 0.23 it compiles fine

**Comment by najamelan** [comment]
Version ws_stream_tungstenite 0.12 has been released that updates to the latest version of tungstenite and async-tungstenite.

**Comment by swanandx** [comment]
Hey @najamelan , looks like async-tungstenite released `0.25` last week as well! which causes the same issue again: 
![image](https://github.com/najamelan/ws_stream_tungstenite/assets/73115739/f303d993-9b75-4ec3-803b-9ac8de5e988c)


can you please update it again? thanks!

ps: for future, would it be better if we don't _pin_ the version with `^`?

**Comment by najamelan** [comment]
I will do another update. Unfortunately these are breaking changes. Until (async)-tungstenite stabilize their API, unfortunately there is nothing we can do downstream but to update all the time. Cargo won't update minor versions until they release 1.x.

**Comment by najamelan** [comment]
0.13.0 was published to crates.

**Comment by swanandx** [comment]
Thank you so much! 🚀
