### ISSUE TITLE
Pulls in native-tls, even if used with rustls

### ISSUE THREAD

**Issue by MathiasKoch** [najamelan/ws_stream_tungstenite#5]
Because this crate enables default features for `tungstenite`, it effectively pulls in `native-tls`, even if the intention is to use it with `rustls` as evidenced by https://github.com/bytebeamio/rumqtt/pull/193

**Comment by najamelan** [comment]
Ah, good catch. I will disable default features. Do you need a 0.3 version with this fixed or is it ok if I put it in the 0.4.0-beta? The 0.4 line uses tokio 0.3.

**Comment by MathiasKoch** [comment]
The 0.4 line is fine for me 👍 thank you!

**Comment by najamelan** [comment]
Nice, because it's a breaking change, so I would have had to move the beta versions to 0.5 and release a 0.4 in between. I'll try to fix this today and I will go over all deps to make sure they are minimal. Sorry for the inconvenience.

**Comment by MathiasKoch** [comment]
Thank you very much! 😀

**Comment by najamelan** [comment]
Ok, version 0.4.0-beta.2 has been released. It strips `thiserror` and sets `default-features: false` on everything else. Thanks for the bug report.
